Minor gpg fix.
Signed-off-by: Johannes Tegnér <johannes@jitesoft.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,16 +17,12 @@ gpg:import:
   image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
   script:
     - |
-      if [ -f keys.out ]; then
-        gpg --import keys.out
-      fi
-    - |
       for key in `cat gpg.txt`; do
         gpg --list-keys ${key} || (
           gpg --keyserver pgp.mit.edu --recv-keys "${key}" ||
           gpg --keyserver keyserver.pgp.com --recv-keys "${key}" ||
           gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "${key}"
-        )
+        ) || echo "Failed to find key for id ${key}"
       done
     - gpg --export > keys.out
   cache:
